# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f41168aff752bfcec747dc2468f0a41b08cef89653ee93a4fe1db41eb4571465243ca11fdbcc87afd760625054d2841b4abc6561a6a6fb6e6e8d0a878e04732

test:
  secret_key_base: d30d8b77c1e7e9648e92af1194dad008971e132cd32076cd845c4a1b9b2dd4e3d425435b63b1ae4d968e3386f550a99846354ecb17f06f148bb5d0e0d140c377

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
